
out/test: out test_moving_average_filter.c ../moving_average_filter.h
	gcc -Wall -Wextra -Werror -std=c99 -I../ test_moving_average_filter.c -o out/test
	./out/test

out: 
	mkdir out

clean:
	rm -rf out
